
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rashik Timalsina
 */
public class Checkout extends javax.swing.JFrame {

    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        txtcheckoutdate.setText(obj.format(date));
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","");
        } catch (ClassNotFoundException |SQLException ex) {
            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
         ShowDataToTable();
    }
    
    public void ShowDataToTable(){
        try {
            pst=conn.prepareStatement("select * from customer where status=?");
            pst.setString(1,"NULL");
            rs=pst.executeQuery();
            ResultSetMetaData rsmd=(ResultSetMetaData) rs.getMetaData();
            int n=rsmd.getColumnCount();
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<=n;i++){
                    
                    v.add(rs.getString("name"));   
                     v.add(rs.getString("mobile")); 
                     v.add(rs.getString("id")); 
                      v.add(rs.getString("roomnumber")); 
                       v.add(rs.getString("bed")); 
                        v.add(rs.getString("roomtype"));
                        v.add(rs.getString("joindate"));
                         v.add(rs.getString("price")); 
                          v.add(rs.getString("nationality")); 
                }
                df.addRow(v); 
            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpriceper = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcheckindate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcheckoutdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtroomnumber = new javax.swing.JTextField();
        btncheckout = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnumberdays = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Checkout");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 232, -1, -1));

        txtname.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 280, 132, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 232, 138, -1));

        txtmobile.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 280, 138, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price Per Day");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 361, -1, -1));

        txtpriceper.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtpriceper, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 415, 119, -1));

        btnsearch.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 0, 0));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check In Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 361, -1, -1));

        txtcheckindate.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtcheckindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 415, 138, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 232, -1, -1));

        txtid.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 280, 119, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check Out Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 361, -1, -1));

        txtcheckoutdate.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtcheckoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 415, 123, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Mobile Number", "CItizenship", "Room Number", "Bed Type", "Room Type", "Check In Date", "Price", "Nationality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 472, 1050, 290));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Room number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtroomnumber.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, -1));

        btncheckout.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btncheckout.setForeground(new java.awt.Color(255, 0, 0));
        btncheckout.setText("CheckOutNow");
        btncheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        btnclear.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 0, 0));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of Days");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 232, -1, -1));

        txtnumberdays.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txtnumberdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 141, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 366, -1, -1));

        txttotal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 415, 141, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1900901.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -14, 1100, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            pst=conn.prepareStatement("select * from customer where roomnumber=? and status=?");
            pst.setString(1,txtroomnumber.getText());
            pst.setString(2,"NULL");
            rs=pst.executeQuery();
            
            if(rs.next()){
                txtname.setText(rs.getString("name"));
                txtmobile.setText(rs.getString("mobile"));
                txtid.setText(rs.getString("id"));
                txtpriceper.setText(rs.getString("price"));
                txtcheckindate.setText(rs.getString("joindate"));
                
            }
            
            String s1,s2;
            s1=txtcheckoutdate.getText();
            s2=rs.getString("joindate");
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            
            Date d1=format.parse(s1);
            Date d2=format.parse(s2);
            long diff=d1.getTime()-d2.getTime();
            int days=(int)diff/(24*60*60*1000);
            if(days==0)
                days=1;
            txtnumberdays.setText(String.valueOf(days));
            double price=Double.parseDouble(rs.getString("price"))*days;
            txttotal.setText(String .valueOf(price));
            
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtname.setText(""); 
        txtmobile.setText("");
        txtid.setText("");
        txtpriceper.setText("");
        txtnumberdays.setText("");
        txtcheckindate.setText("");
        //txtcheckoutdate.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckoutActionPerformed
        try {
            pst=conn.prepareCall("update customer set status=? where roomnumber=? and joindate=?");
            pst.setString(1,"Checked-Out");
            pst.setString(2,txtroomnumber.getText());
            pst.setString(3,txtcheckindate.getText());
            pst.executeUpdate();
            
              pst=conn.prepareCall("update room set Status=? where Roomnumber=?");
              pst.setString(1,"NOT-BOOKED");
              pst.setString(2,txtroomnumber.getText());
              pst.executeUpdate();
              
              JOptionPane.showMessageDialog(this,"Checked Out Successfully");
              
              ShowDataToTable();
              
        txtname.setText(""); 
        txtmobile.setText("");
        txtid.setText("");
        txtpriceper.setText("");
        txtnumberdays.setText("");
        txtcheckindate.setText("");
        //txtcheckoutdate.setText("");
        txttotal.setText("");
              
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btncheckoutActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckout;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcheckindate;
    private javax.swing.JTextField txtcheckoutdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumberdays;
    private javax.swing.JTextField txtpriceper;
    private javax.swing.JTextField txtroomnumber;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
