
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rashik Timalsina
 */
public class CustomerCheckin extends javax.swing.JFrame {

    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","");
        } catch (ClassNotFoundException |SQLException ex) {
            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Rashik();
    }

    public void Rashik()
    {
        try {
            pst=conn.prepareStatement("select Roomnumber from room where Bed=? and Roomtype=? and Status=?");
            pst.setString(1,cmbbedtype.getItemAt(cmbbedtype.getSelectedIndex()));
            pst.setString(2,cmbroomtype.getItemAt(cmbroomtype.getSelectedIndex())); 
            pst.setString(3,"NOT-BOOKED");
            rs=pst.executeQuery();
            cmbroomnumber.removeAllItems();
            while(rs.next()){
                cmbroomnumber.addItem(rs.getString("Roomnumber"));
            }
             pst=conn.prepareStatement("select Price from room where Roomnumber=?");
             pst.setString(1,cmbroomnumber.getItemAt(cmbroomnumber.getSelectedIndex()));
             rs=pst.executeQuery();
             
             if(rs.next()){
                             txtprice.setText(rs.getString("Price"));
        }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbgender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcitizenship = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbbedtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        cmbroomnumber = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Checkin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 100, 201, -1));

        txtname.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 142, 201, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 211, 201, -1));

        txtmobile.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 253, 201, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 327, 201, -1));

        cmbgender.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });
        getContentPane().add(cmbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 369, 201, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 438, 201, -1));

        txtnationality.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        getContentPane().add(txtnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 480, 201, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Citizenship no");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 554, 201, -1));

        txtcitizenship.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        getContentPane().add(txtcitizenship, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 596, 201, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check in Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 200, -1));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 142, 200, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BedType");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 211, 200, -1));

        cmbbedtype.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cmbbedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        cmbbedtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbedtypeItemStateChanged(evt);
            }
        });
        cmbbedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbedtypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 257, 200, 26));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RoomType");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 331, 195, -1));

        cmbroomtype.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cmbroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        cmbroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbroomtypeItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 373, 200, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RoomNumber");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 438, 195, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 554, 200, -1));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 596, 200, -1));

        btncheckin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btncheckin.setForeground(new java.awt.Color(255, 0, 0));
        btncheckin.setText("Checkin Now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, -1, -1));

        btnclear.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 0, 0));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, -1, -1));

        cmbroomnumber.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cmbroomnumber.setName(""); // NOI18N
        cmbroomnumber.setPreferredSize(new java.awt.Dimension(37, 32));
        getContentPane().add(cmbroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 481, 200, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1900901.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1130, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void cmbbedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbedtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbedtypeActionPerformed

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbbedtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbedtypeItemStateChanged
            Rashik();
    }//GEN-LAST:event_cmbbedtypeItemStateChanged

    private void cmbroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbroomtypeItemStateChanged
             Rashik();
    }//GEN-LAST:event_cmbroomtypeItemStateChanged

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
        if(txtname.getText().equals("")){
            txtname.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
            
        }
        else if(txtmobile.getText().equals("")){
            txtmobile.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
            
        }
        else if(txtnationality.getText().equals("")){
            txtnationality.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
            
        }
        else if(txtcitizenship.getText().equals("")){
            txtcitizenship.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
            
        }
          else{
            try {
                pst=conn.prepareStatement("insert into customer(name,mobile,gender,nationality,id,joindate,bed,roomtype,roomnumber,price,status)values(?,?,?,?,?,?,?,?,?,?,?)"); 
                pst.setString(1,txtname.getText());  
                pst.setString(2,txtmobile.getText());
                pst.setString(3,cmbgender.getItemAt(cmbgender.getSelectedIndex()));
                pst.setString(4,txtnationality.getText());
                pst.setString(5,txtcitizenship.getText());
                pst.setString(6,txtdate.getText());
                pst.setString(7,cmbbedtype.getItemAt(cmbbedtype.getSelectedIndex()));
                pst.setString(8,cmbroomtype.getItemAt(cmbroomtype.getSelectedIndex()));
                pst.setString(9,cmbroomnumber.getItemAt(cmbroomnumber.getSelectedIndex()));
                pst.setString(10,txtprice.getText());
                pst.setString(11,"NULL");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Customer Checked-In Successfully ");
                txtname.setText("");
                txtcitizenship.setText("");
                txtmobile.setText("");
                txtnationality.setText("");
                
                pst=conn.prepareStatement("update room set status=? where roomnumber=?");
                pst.setString(1,"BOOKED");
                pst.setString(2,cmbroomnumber.getItemAt(cmbroomnumber.getSelectedIndex()));
                pst.executeUpdate();
                
                Rashik();
                     
            } catch (SQLException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
            }
          
          
          }
    }//GEN-LAST:event_btncheckinActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtname.setText(""); 
        txtcitizenship.setText("");
        txtmobile.setText("");
        txtnationality.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> cmbbedtype;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbroomnumber;
    private javax.swing.JComboBox<String> cmbroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcitizenship;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
